### ISSUE TITLE
Repeatable::toArray() returns string for new node

### ISSUE THREAD

**Issue by koehnlein** [mireo91/RepeatableFields#10]
Neos 8.2
PHP 8.1

When I create a new node, my repeatable property is set to an empty string until I really create some repeatable nodes. Unfortunatly, the empty string breaks my fusion implementation with `Neos.Fusion:Loop` because the count method in Neos' LoopImplementation tries to call Repeatable::count(), which calls Repeatable::toArray(), which returns a string that cannot be counted.

```
Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in /var/www/html/Data/Temporary/Development/SubContextDdev/Cache/Code/Flow_Object_Classes/Mireo_RepeatableFields_Model_Repeatable.php:133 Stack trace: #0 /var/www/html/Data/Temporary/Development/SubContextDdev/Cache/Code/Flow_Object_Classes/Mireo_RepeatableFields_Model_Repeatable.php(133): count('') #1 [internal function]: Mireo\RepeatableFields\Model\Repeatable_Original-&gt;count() #2 /var/www/html/Data/Temporary/Development/SubContextDdev/Cache/Code/Flow_Object_Classes/Neos_Fusion_FusionObjects_MapImplementation.php(87): count(Object(Mireo\RepeatableFields\Model\Repeatable)) #3 /var/www/html/Data/Temporary/Development/SubContextDdev/Cache/Code/Flow_Object_Classes/Neos_Fusion_FusionObjects_LoopImplementation.php(42): Neos\Fusion\FusionObjects\MapImplementation_Original-&gt;evaluate() #4 /var/www/html/Data/Temporary/Development/SubContextDdev/Cache/Code/Flow_Object_Classes/Neos_Fusion_Core_Runtime.php(468): Neos\Fusion\FusionObjects\LoopImplementation_Original-&gt;evaluate() #5 /var/www/html/Data/Temporary/Development/SubContextDdev/Cache/Code/Flow_Object_Classes/Neos_Fusion_Core_Runtime.php(420): Neos\Fusion\Core\Runtime_Original-&gt;evaluateObjectOrRetrieveFromCache(Object(Neos\Fusion\FusionObjects\LoopImplementation), 'root&lt;Neos.Fusio...', Array, Array) #6 /var/www/html/Packages/Application/Neos.Fusion/Classes/FusionObjects/Helpers/LazyProps.php(70): Neos\Fusion\Core\Runtime_Original-&gt;evaluate('root&lt;Neos.Fusio...', Object(Neos\Fusion\FusionObjects\ComponentImplementation)) #7 /var/www/html/Packages/Application/Neos.Fusion/Classes/FusionObjects/Helpers/LazyProps.php(94): Neos\Fusion\FusionObjects\Helpers\LazyProps-&gt;offsetGet('items') #8 /var/www/html/Packages/Framework/Neos.Flow/Classes/Error/Debugger.php(175): Neos\Fusion\FusionObjects\Helpers\LazyProps-&gt;current() #9 /var/www/html/Packages/Framework/Neos.Flow/Classes/Error/Debugger.php(143): Neos\Flow\Error\Debugger::renderArrayDump(Object(Neos\Fusion\FusionObjects\Helpers\LazyProps), 2, true, false) #10 /var/www/html/Packages/Framework/Neos.Flow/Classes/Error/Debugger.php(177): Neos\Flow\Error\Debugger::renderDump(Object(Neos\Fusion\FusionObjects\Helpers\LazyProps), 1, true, false) #11 /var/www/html/Packages/Framework/Neos.Flow/Classes/Error/Debugger.php(353): Neos\Flow\Error\Debugger::renderArrayDump(Array, 0, true) #12 /var/www/html/Packages/Framework/Neos.Flow/Classes/Error/DebugExceptionHandler.php(130): Neos\Flow\Error\Debugger::getBacktraceCode(Array) #13 /var/www/html/Packages/Framework/Neos.Flow/Classes/Error/DebugExceptionHandler.php(74): Neos\Flow\Error\DebugExceptionHandler-&gt;renderStatically(500, Object(TypeError)) #14 /var/www/html/Packages/Framework/Neos.Flow/Classes/Error/AbstractExceptionHandler.php(128): Neos\Flow\Error\DebugExceptionHandler-&gt;echoExceptionWeb(Object(TypeError)) #15 [internal function]: Neos\Flow\Error\AbstractExceptionHandler-&gt;handleException(Object(TypeError)) #16 {main} thrown in /var/www/html/Data/Temporary/Development/SubContextDdev/Cache/Code/Flow_Object_Classes/Mireo_RepeatableFields_Model_Repeatable.php on line 133
```

**Comment by mireo91** [comment]
@koehnlein thx for your input. I will take a look for and will add it to next release.
